### ISSUE TITLE
Error when compile webby

### ISSUE THREAD

**Issue by tcollignon** [tesla/m2eclipse-webby#13]
Hi,

I'm trying to compile m2eclipse-webby, with `mvn clean install`and I have this error : 

````
mvn clean install
[INFO] Scanning for projects...
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[INFO] Computing target platform for MavenProject: org.sonatype.m2e.webby:org.sonatype.m2e.webby:0.2.2-SNAPSHOT @ /Users/thomascollignon/Documents/Workspace_eclipse/webbyTomee/org.sonatype.m2e.webby/pom.xml
[INFO] Adding repository http://repository.sonatype.org/content/sites/forge-sites/eclipse-commons/1.1.7/N/1.1.7.201105091728
[INFO] Resolving dependencies of MavenProject: org.sonatype.m2e.webby:org.sonatype.m2e.webby:0.2.2-SNAPSHOT @ /Users/thomascollignon/Documents/Workspace_eclipse/webbyTomee/org.sonatype.m2e.webby/pom.xml
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.os=macosx, osgi.ws=cocoa, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.sonatype.m2e.webby 0.2.2.qualifier
[ERROR]   Missing requirement: org.sonatype.m2e.webby 0.2.2.qualifier requires 'bundle org.eclipse.ui 0.0.0' but it could not be found
[ERROR] 
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.ui.console 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.ui.ide 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.expressions 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.resources 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.variables 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.debug.core 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.debug.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.core 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.debug 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.debug.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.launching 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.m2e.core [1.0.0,2.0.0).; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.m2e.maven.runtime [1.0.0,2.0.0).; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.m2e.jdt [1.0.0,2.0.0).; No solution found because the problem is unsatisfiable.] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.ui.console 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.ui.ide 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.expressions 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.resources 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.variables 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.debug.core 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.debug.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.core 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.debug 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.debug.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.launching 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.m2e.core [1.0.0,2.0.0).; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.m2e.maven.runtime [1.0.0,2.0.0).; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.m2e.jdt [1.0.0,2.0.0).; No solution found because the problem is unsatisfiable.]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.ui.console 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.ui.ide 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.expressions 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.resources 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.core.variables 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.debug.core 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.debug.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.core 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.debug 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.debug.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.launching 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.jdt.ui 0.0.0.; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.m2e.core [1.0.0,2.0.0).; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.m2e.maven.runtime [1.0.0,2.0.0).; Unable to satisfy dependency from org.sonatype.m2e.webby 0.2.2.qualifier to bundle org.eclipse.m2e.jdt [1.0.0,2.0.0).; No solution found because the problem is unsatisfiable.]
	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:98)
	at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:63)
	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:166)
	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:103)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies(P2DependencyResolver.java:352)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies(P2DependencyResolver.java:325)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:107)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	... 11 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
````

Do you know why ?

Thank you

**Comment by tcollignon** [comment]
I remember that I have same kind of problem before, and the answer was a misake in parent pom locally (don't know why exactly).

This is the good pom (from @ifedorenko answer on mailing list): 

````
Attached is contents of [1] that I see, Luna repository is around line 63. If your version of tycho.support:0.0.12 is different, either you have a local/altered version or somebody is messing with your connection to central

[1]
https://repo1.maven.org/maven2/io/tesla/tycho/tycho-support/0.0.12/tycho-support-0.0.12.pom
````

**Comment by jvanzyl** [comment]
It's building in CI correctly. What version of Maven are you using? Can you provide the mvn -v output please?

https://ci.takari.io/job/m2eclipse-webby/31/console

**Comment by tcollignon** [comment]
````
mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /Applications/apache-maven-3.3.3
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"
````

**Comment by tcollignon** [comment]
If I look at tycho-support-0.0.15 I have not Luna repository (and it's present in 0.0.12), it's OK? or not? Thank you

**Comment by jvanzyl** [comment]
If you have an update for webby using the latest tycho-support please make a pull request. We still do not create target platforms for most of the connectors so updating to the latest is fine. If you have it working send it along and I'll try it.

**Comment by tcollignon** [comment]
I don't use tycho-support myself (I just look at the source, and I see tycho 0.0.15), I try to find where can be the problem. Maybe in mac-os-x profile?
I will try to submit my pull request and you will see the result

**Comment by tcollignon** [comment]
I have submit the #14 pull request

**Comment by tcollignon** [comment]
I have test this on windows and same problem, I have this resolution in the log
````
[INFO] Computing target platform for MavenProject: org.sonatype.m2e.webby:org.sonatype.m2e.webby:0.2.2-SNAPSHOT @ D:\java\workspaces\developpement_test\
m2eclipse-webby\org.sonatype.m2e.webby\pom.xml
[INFO] Adding repository http://repository.sonatype.org/content/sites/forge-sites/eclipse-commons/1.1.7/N/1.1.7.201105091728
[INFO] Resolving dependencies of MavenProject: org.sonatype.m2e.webby:org.sonatype.m2e.webby:0.2.2-SNAPSHOT @ D:\java\workspaces\developpement_test\m2ec
lipse-webby\org.sonatype.m2e.webby\pom.xml
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.ws=win32, osgi.os=win32, osgi.arch=x86_64, org.eclipse.update.install.features=true}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.sonatype.m2e.webby 0.2.2.qualifier
[ERROR]   Missing requirement: org.sonatype.m2e.webby 0.2.2.qualifier requires 'bundle org.eclipse.ui 0.0.0' but it could not be found
[ERROR]
````

And in your CI you have : 
````
[INFO] Computing target platform for MavenProject: org.sonatype.m2e.webby:org.sonatype.m2e.webby:0.2.2-SNAPSHOT @ /home/ci/hudson-work/jobs/m2eclipse-webby/workspace/org.sonatype.m2e.webby/pom.xml
[INFO] Adding repository http://repository.sonatype.org/content/sites/forge-sites/eclipse-commons/1.1.7/N/1.1.7.201105091728
[INFO] Adding repository https://otto.takari.io/content/sites/m2e.extras/m2e/1.6.0/N/LATEST
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/releases/luna
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201406250900/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201409261001/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201501121000/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201502271000/ (0B at 0B/s)
````

**Comment by tcollignon** [comment]
I have compared io.takari.tycho:0.15.0 from : 
https://repo1.maven.org/maven2/io/takari/tycho/tycho-support/0.15.0/tycho-support-0.15.0.pom 
and from my maven local repo build with artifactory. And I have not this section : 
````
<repositories>
    <!-- 
      The org.eclipse.m2e.tests.common bundle is deployed to the m2e releases repository but is not 
      part of the simultaneous release. The connectors use this bundle for testing so we need to
      be able to pick it up.
    -->
    <repository>
      <id>m2e-core</id>
      <url>${m2e-core.url}</url>
      <layout>p2</layout>
    </repository>
    <repository>
      <id>luna</id>
      <url>http://download.eclipse.org/releases/luna</url>
      <layout>p2</layout>
    </repository>
  </repositories>
````

It's unbelievable ! In artifactory webapp, it's here, and in my local repo, no !
Anyway it's artifactory bug, I can now compile webby.
I close this issue.

So my PR is ok now, can you take a look at this when you have time? #14 
 
Thanks
